<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="user-PC" failures="0" tests="1" name="com.TestNG.ExceptionTimeOutTest" time="0.030" errors="1" timestamp="2019-11-19T16:28:00 IST" skipped="0">
  <testcase classname="com.TestNG.ExceptionTimeOutTest" name="infiniteLoopTest" time="0.030">
    <error message="
Expected exception of type class java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method com.TestNG.ExceptionTimeOutTest.infiniteLoopTest() didn&#039;t finish within the time-out 2" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method com.TestNG.ExceptionTimeOutTest.infiniteLoopTest() didn't finish within the time-out 2
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:719)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:616)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.testng.internal.thread.ThreadTimeoutException: Method com.TestNG.ExceptionTimeOutTest.infiniteLoopTest() didn't finish within the time-out 2
at java.base@12.0.2/java.lang.System.arraycopy(Native Method)
at java.base@12.0.2/java.io.BufferedOutputStream.write(BufferedOutputStream.java:129)
at java.base@12.0.2/java.io.PrintStream.write(PrintStream.java:559)
at java.base@12.0.2/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
at java.base@12.0.2/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
at java.base@12.0.2/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
at java.base@12.0.2/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:184)
at java.base@12.0.2/java.io.PrintStream.write(PrintStream.java:606)
at java.base@12.0.2/java.io.PrintStream.print(PrintStream.java:676)
at java.base@12.0.2/java.io.PrintStream.println(PrintStream.java:812)
at app//com.TestNG.ExceptionTimeOutTest.infiniteLoopTest(ExceptionTimeOutTest.java:11)
at java.base@12.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@12.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base@12.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@12.0.2/java.lang.reflect.Method.invoke(Method.java:567)
at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:51)
at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at java.base@12.0.2/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base@12.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@12.0.2/java.lang.Thread.run(Thread.java:835)
]]>
    </error>
  </testcase> <!-- infiniteLoopTest -->
</testsuite> <!-- com.TestNG.ExceptionTimeOutTest -->
